version: '3.4'
services:
  geoserver:
    image: "quay.io/alessiogiambrone/isochrone_server"
    ports:
      - 8080
    healthcheck:
      test: curl --fail -s http://localhost:8080/health || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
    environment:
      - PBF_PATH=/pbf
    volumes:
      - ./pbf:/pbf
  uglyserver:
    image: "alessiogiambrone/ugly_server:0.0.1"
    ports:
      - 8585
    volumes:
      - ./ugly_conf/config.yaml:/conf/config.yaml
  mapserver:
    image: overv/openstreetmap-tile-server:1.3.10
    command: "run"
    volumes:
      - openstreetmap-data:/var/lib/postgresql/12/main
    ports:
      - 80
  nginx:
    image: "nginx:1.16.1-alpine"
    ports:
      - "9090:80"
    volumes:
      - ./static:/usr/share/nginx/html
      - ./static/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static/nginx.default.conf:/etc/nginx/conf.d/default.conf

volumes:
  openstreetmap-data:
    external:
      name: openstreetmap-data

